import React from 'react'
import Head from 'next/head'
import Puzzle from './Puzzle'
function SlidingPuzzle() {
  return (
    <>
      <Head>
        <title>Sliding Puzzle</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <Puzzle/>
    </>
  )
}

export default SlidingPuzzle